version: "3.8"

services:
  rick-morty-app:
    container_name: rick-morty-dashboard
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
      - TMDB_API_KEY=${TMDB_API_KEY:-YOUR_TMDB_API_KEY_HERE}
    restart: unless-stopped
    networks:
      - rick-morty-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:4200/",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  rick-morty-network:
    name: rick-morty-prod-network
